# Generated by Django 5.0.1 on 2024-02-21 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 14, 40, 24, 447337, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
